name: npm release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm publish
        run: npm publish --provenance --access public
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
